import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Figtree, Playfair_Display, Inter } from "next/font/google";
import { Dancing_Script } from 'next/font/google';
import "./globals.css";

const figtree = Figtree({
  subsets: ["latin"],
  //variable: "--font-figtree",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  //variable: "--font-playfair",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// configure Inter
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  variable: "--font-dancing-script",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
